//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GridMaker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point ComposerLocation {
            get {
                return ((global::System.Drawing.Point)(this["ComposerLocation"]));
            }
            set {
                this["ComposerLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700, 325")]
        public global::System.Drawing.Size ComposerSize {
            get {
                return ((global::System.Drawing.Size)(this["ComposerSize"]));
            }
            set {
                this["ComposerSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ComposerMaximized {
            get {
                return ((bool)(this["ComposerMaximized"]));
            }
            set {
                this["ComposerMaximized"] = value;
            }
        }
		
		[global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ComposerMinimized {
            get {
                return ((bool)(this["ComposerMinimized"]));
            }
            set {
                this["ComposerMinimized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point SelectorLocation {
            get {
                return ((global::System.Drawing.Point)(this["SelectorLocation"]));
            }
            set {
                this["SelectorLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("402, 454")]
        public global::System.Drawing.Size SelectorSize {
            get {
                return ((global::System.Drawing.Size)(this["SelectorSize"]));
            }
            set {
                this["SelectorSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SelectorMaximized {
            get {
                return ((bool)(this["SelectorMaximized"]));
            }
            set {
                this["SelectorMaximized"] = value;
            }
        }
		
		[global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SelectorMinimized {
            get {
                return ((bool)(this["SelectorMinimized"]));
            }
            set {
                this["SelectorMinimized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point PreviewLocation {
            get {
                return ((global::System.Drawing.Point)(this["PreviewLocation"]));
            }
            set {
                this["PreviewLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000, 400")]
        public global::System.Drawing.Size PreviewSize {
            get {
                return ((global::System.Drawing.Size)(this["PreviewSize"]));
            }
            set {
                this["PreviewSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PreviewMaximized {
            get {
                return ((bool)(this["PreviewMaximized"]));
            }
            set {
                this["PreviewMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PreviewMinimized {
            get {
                return ((bool)(this["PreviewMinimized"]));
            }
            set {
                this["PreviewMinimized"] = value;
            }
        }
    }
}
